### ISSUE TITLE
Outdated readme

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-l10n/sumo-l10n#1]
IMO it should link to some http://kitsune.readthedocs.org/en/latest/localization.html anchor, but do not know which one you prefer. @mythmon @flodolo

**Comment by flodolo** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1255885#c6

Personally I think we should get rid completely of bash scripts and instructions, those belong to the code repository.

**Comment by flodolo** [comment]
Updated README in https://github.com/mozilla-l10n/sumo-l10n/commit/ca3dcfe77153bee29a89a6f0cd3c5a5ecdf13d0a
