### ISSUE TITLE
Sync web page with Pontoon for sv(sv-SE)

### ISSUE THREAD

**Issue by andy-moz** [mozilla-l10n/sumo-l10n#114]
New strings translated in Pontoon are not synced with web page support.mozilla.org for Swedish https://support.mozilla.org/sv/. Same thing for the web page about contributions https://support.mozilla.org/sv/contribute

**Comment by andy-moz** [comment]
Please copy translated string from files django.po and djangojs.po in [sv-SE](https://github.com/mozilla-l10n/sumo-l10n/tree/master/sv_SE/LC_MESSAGES) to directory [sv](https://github.com/mozilla-l10n/sumo-l10n/tree/master/sv/LC_MESSAGES). The web page is not synchronized with the directory.

**Comment by peiying2** [comment]
@akatsoulas let's make sure the locale code is fixed or gets redirected so the community's work is not wasted.

**Comment by flodolo** [comment]
Note: this could be done via GitHub actions (copy sv-SE to sv). This is how it's done in Firefox accounts, IIRC also for fy-NL.

**Comment by escattone** [comment]
> Note: this could be done via GitHub actions (copy sv-SE to sv). This is how it's done in Firefox accounts, IIRC also for fy-NL.

@flodolo Thanks, that's a great idea.

**Comment by flodolo** [comment]
BTW, this is the code in question https://github.com/mozilla/fxa-content-server-l10n/blob/main/scripts/extract_strings.sh#L110-L130

**Comment by akatsoulas** [comment]
The GitHub Action for syncing the locales is now live
