### ISSUE TITLE
Typo in English

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/sumo-l10n#136]
There is a typo in this string: `[Fox sticking it's head out from behind a stack of boxes.](https://pontoon.mozilla.org/it/sumo/LC_MESSAGES/djangojs.po/?string=284742)` 
 - `it's head` should be `its head`.
 
@akatsoulas

**Comment by emilghittasv** [comment]
@akatsoulas This is the `alt` attribute value for the doodle image from step 2 of the switching-devices wizard.

**Comment by akatsoulas** [comment]
Fixed in https://github.com/mozilla/kitsune/pull/5693
