### ISSUE TITLE
Extra ' in the code 

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/sumo-l10n#143]
https://pontoon.mozilla.org/zh-CN/sumo/LC_MESSAGES/django.po/?string=286297 

there is an extra *'* at the end of the string: `Continuing with your Mozilla account means you have agreed with the <a href="%(terms_url)s">Terms and Conditions</a> and <a href="%(privacy_url)s">Privacy Policy</a>.'`

@akatsoulas

**Comment by emilghittasv** [comment]
This was also reported in SUMO repo -> https://github.com/mozilla/sumo/issues/1512

**Comment by akatsoulas** [comment]
Fixed in https://github.com/mozilla/kitsune/pull/5693
