### ISSUE TITLE
Update Sumo page

### ISSUE THREAD

**Issue by andy-moz** [mozilla-l10n/sumo-l10n#18]
Update needed for support.mozilla.org with the new strings extracted from Kitsune, see issue #8. I translated the new strings 3 weeks ago in Pontoon. Nothing has updated on the Sumo page.

**Comment by akatsoulas** [comment]
There was a production release that pushed new strings out the previous Monday on the 25th of November. Could you include a couple of pages that should have been translated but they are not?

**Comment by andy-moz** [comment]
First page https://support.mozilla.org/sv/?fpa=1 and the pages of Firefox Preview https://support.mozilla.org/sv/products/firefox-preview and Firefox Lockwise https://support.mozilla.org/sv/products/firefox-lockwise.

**Comment by akatsoulas** [comment]
@andy-moz is this still an issue? In the pages that you linked most of the strings are translated. Is this issue related to the remaining strings?

**Comment by andy-moz** [comment]
Yes, this is still an issue. New strings are translated in pontoon but are not updated/reflected in the Sumo web page. Example string "Early version of an experimental Firefox browser for Android." are translated in Pontoon, but still is in English on the web page after a month.

**Comment by akatsoulas** [comment]
This issue should be resolved. Please re-open the issue if this is not the case.

**Comment by andy-moz** [comment]
Thanks. Finally, good job.
