### ISSUE TITLE
String is hardcoded for user name already exists

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/sumo-l10n#45]
Issue: `A user with that username already exists` is hard coded. 

![image](https://user-images.githubusercontent.com/6090393/115276523-f99b4180-a0f7-11eb-9e87-7fadeb3f37a0.png)

Looks like the strings with the same content were localized a while back but not leveraged: https://pontoon.mozilla.org/zh-CN/sumo/all-resources/?search=A+user+with+that+us&string=133264.

**Comment by xiaopangju** [comment]
Hi, I'm the reporter(my username is [bingchuanjuzi](https://support.mozilla.org/zh-CN/user/bingchuanjuzi) now) of this issue.
Also, I can't find the string you mentioned.
![cant-find-string](https://user-images.githubusercontent.com/56964531/116688253-0158c100-a9e9-11eb-96d1-5c96a97befb8.png)

**Comment by LeoMcA** [comment]
The string that had been localized but wasn't being used was part of a set of locale files no longer being used in the project, which we removed here: https://github.com/mozilla-l10n/sumo-l10n/pull/47

This issue can be tracked here: https://github.com/mozilla/sumo-project/issues/841
