### ISSUE TITLE
String is hardcoded for Ensure this value has at most 10000 characters (it has xxx).

### ISSUE THREAD

**Issue by xiaopangju** [mozilla-l10n/sumo-l10n#48]
Issue：`Ensure this value has at most 10000 characters (it has XXX).` is hardcoded.
![图片](https://user-images.githubusercontent.com/56964531/116798122-1e8fab80-ab1f-11eb-9cd4-236cf5d6dfb9.png)

**Comment by xiaopangju** [comment]
@akatsoulas

**Comment by LeoMcA** [comment]
@xiaopangju thanks for this report, it'll also be a result of the mismatched locale codes between sumo (zh-CN) and django (zh-Hans). You can track the related issue here: https://github.com/mozilla/sumo-project/issues/841
