### ISSUE TITLE
Merging locales bn-BD and bn-IN to single locale bn

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/sumo-l10n#6]
We are going to merge the two locales into one to fully utilize the community resources. The plan is:

Dev:
* SUMO creates a bn folder at repo
* Move bn-IN repo content to bn repo and confirm it's all there (bn-IN has more content in comparison)
* Remove bn-BD, bn-IN repos

Pontoon (l10n):
* Pontoon dev migrates the data to bn (this includes contributors histories)
* L10n PM confirms the update and closes this issue.

@nukeador could you connect me with the right developer for help with this effort? Is Giorgos the right person? I can't find him here.

**Comment by nukeador** [comment]
You should reach out @akatsoulas who is now our main kitsune developer.

**Comment by peiying2** [comment]
This is a wrap! Thank you!

**Comment by peiying2** [comment]
I will wait until the code is pushed on production.

**Comment by akatsoulas** [comment]
This is now deployed in prod.

**Comment by peiying2** [comment]
Thanks. Done on Pontoon side as well.
