### ISSUE TITLE
Firefox Lockwise and Firefox Preview strings not in Pontoon

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/sumo-l10n#8]
A community contributor reported that there have been no new strings added to Pontoon for a while. He would like to see Firefox Lockwise, Firefox Preview, Firefox Private Network topics open for localization.

@akatsoulas

**Comment by peiying2** [comment]
Landing page: https://support.mozilla.org/de/

**Comment by pierreneter** [comment]
I think we need to extract new strings from https://github.com/mozilla/kitsune/, it's been a long time since the last extract on Dec 18, 2018. https://github.com/mozilla-l10n/sumo-l10n/commit/61e0d09b41271e5bfdfd09ce7ae136d99113bfed

**Comment by pierreneter** [comment]
ok, let me help update

**Comment by akatsoulas** [comment]
Closing this after #11. Thanks @pierreneter for working on this.

**Comment by andy-moz** [comment]
We need to update support.mozilla.org with the new translated strings. I translated the new strings 3 weeks ago. Nothing has updated on the Sumo page.
